name: MATRiX

on: [push]

jobs:
  echo-job:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]  # 20 runners
    steps:
      - name: Echo message
        run: echo "salam Im here from runner ${{ matrix.runner }}"
